function comparison = build_paper_comparison()
% Build the matched Miller-triangularity ITG comparison for Section 4.3.

caseRoot = fileparts(mfilename('fullpath'));
projectRoot = fileparts(fileparts(fileparts(caseRoot)));
templateFile = fullfile(projectRoot, 'analysis', ...
    'cgyro_standard_miller_ae', 'ky030', 'input.cgyro');
cgyroRoot = fullfile(projectRoot, 'analysis', ...
    'cgyro_standard_miller_triangularity');
mgkFile = fullfile(caseRoot, 'miller_itg_triangularity_mgk.mat');

delta = (-0.4:0.2:0.4).';
caseNames = {'delta_m0p4', 'delta_m0p2', 'delta_0p0', ...
    'delta_p0p2', 'delta_p0p4'};
validateCgyroInputs(templateFile, cgyroRoot, caseNames, delta);

numCases = numel(delta);
cgyroOmega = complex(NaN(numCases, 1));
thetaCgyro = cell(numCases, 1);
phiCgyroRaw = cell(numCases, 1);
for index = 1:numCases
    directory = fullfile(cgyroRoot, caseNames{index});
    [cgyroOmega(index), thetaCgyro{index}, phiCgyroRaw{index}] = ...
        readCgyroCase(directory);
end

mgk = load(mgkFile, 'delta', 'omegaR0OverCs', 'omegaAOverCs', ...
    'thetaMgk', 'phiMgk', 'continuationOverlap', ...
    'baseConfig', 'references');
validateMgkData(mgk, delta);
aOverR0 = mgk.references.minorRadiusScale / ...
    mgk.references.majorRadiusScale;
mgkOmega = mgk.omegaR0OverCs(:) * aOverR0;
assert(max(abs(mgkOmega - mgk.omegaAOverCs(:))) < 1e-12, ...
    'The stored MGK frequency normalizations are inconsistent.');

thetaMgk = mgk.thetaMgk(:);
phiMgkRaw = mgk.phiMgk(:);
phiCgyro = cell(numCases, 1);
phiMgk = cell(numCases, 1);
overlap = NaN(numCases, 1);
for index = 1:numCases
    [phiCgyro{index}, phiMgk{index}, overlap(index)] = alignModes( ...
        thetaCgyro{index}, phiCgyroRaw{index}, ...
        thetaMgk{index}, phiMgkRaw{index});
end

relativeComplexDifference = abs(mgkOmega - cgyroOmega) ./ ...
    abs(cgyroOmega);
displayed = [1, 3, 5];
assert(all(real(mgkOmega) < 0) && all(real(cgyroOmega) < 0), ...
    'A triangularity point left the negative-frequency ITG branch.');
assert(max(relativeComplexDifference) <= 0.02, ...
    'MGK--CGYRO complex-frequency difference exceeds 2%%.');
assert(all(overlap(displayed) > 0.995), ...
    'A displayed MGK--CGYRO mode overlap is not above 0.995.');

comparison = table(delta, real(mgkOmega), imag(mgkOmega), ...
    real(cgyroOmega), imag(cgyroOmega), ...
    relativeComplexDifference, overlap, ...
    'VariableNames', {'delta', 'mgkOmegaR', 'mgkGamma', ...
    'cgyroOmegaR', 'cgyroGamma', ...
    'relativeComplexDifference', 'overlap'});
csvFile = fullfile(caseRoot, ...
    'miller_itg_triangularity_cgyro_mgk.csv');
matFile = fullfile(caseRoot, ...
    'miller_itg_triangularity_cgyro_mgk.mat');
writetable(comparison, csvFile);
save(matFile, 'comparison', 'delta', 'mgkOmega', 'cgyroOmega', ...
    'thetaMgk', 'phiMgk', 'thetaCgyro', 'phiCgyro', ...
    'relativeComplexDifference', 'overlap', 'templateFile', ...
    'cgyroRoot', '-v7.3');

figureDirectory = fullfile(fileparts(projectRoot), 'paper', 'figures');
if ~isfolder(figureDirectory)
    mkdir(figureDirectory);
end
figureFile = fullfile(figureDirectory, ...
    'miller_itg_triangularity_cgyro_mgk.pdf');
plotComparison(delta, mgkOmega, cgyroOmega, thetaMgk, phiMgk, ...
    thetaCgyro, phiCgyro, displayed, figureFile);

fprintf('Matched Miller-triangularity ITG comparison\n');
fprintf('  maximum relative complex-frequency difference: %.3f%%\n', ...
    100 * max(relativeComplexDifference));
fprintf('  displayed mode overlaps: %.6f, %.6f, %.6f\n', ...
    overlap(displayed));
fprintf('  data:   %s\n', csvFile);
fprintf('  figure: %s\n', figureFile);
disp(comparison)
end

function validateCgyroInputs(templateFile, caseRoot, caseNames, delta)
assert(isfile(templateFile), 'Missing sole CGYRO template: %s', ...
    templateFile);
templateText = readExactText(templateFile);
templateNormalized = normalizeDeltaLine(templateText, templateFile);

keys = {'N_THETA', 'N_RADIAL', 'N_ENERGY', 'E_MAX', 'N_XI', ...
    'DELTA_T', 'MAX_TIME', 'ERROR_TOL', 'FREQ_TOL', ...
    'RMAJ', 'RMIN', 'Q', 'S', 'DLNNDR_1', 'DLNTDR_1', ...
    'TEMP_1', 'TEMP_AE', 'KY', 'KAPPA', 'S_KAPPA', ...
    'S_DELTA', 'SHIFT', 'BETA_STAR_SCALE'};
expected = [32, 9, 16, 10, 32, 0.01, 100, 1e-6, 1e-4, ...
    3, 0.5, 2, 1, 1, 3, 1, 1, 0.3, 1, 0, 0, 0, 0];
for index = 1:numel(keys)
    actual = readNumericSetting(templateText, keys{index}, templateFile);
    tolerance = 1e-12 * max(1, abs(expected(index)));
    assert(abs(actual - expected(index)) <= tolerance, ...
        'Unexpected %s in the sole CGYRO template.', keys{index});
end

for index = 1:numel(caseNames)
    inputFile = fullfile(caseRoot, caseNames{index}, 'input.cgyro');
    assert(isfile(inputFile), 'Missing CGYRO input: %s', inputFile);
    caseText = readExactText(inputFile);
    normalized = normalizeDeltaLine(caseText, inputFile);
    assert(isequal(normalized, templateNormalized), ...
        'CGYRO input differs from the template outside DELTA: %s', ...
        inputFile);
    caseDelta = readNumericSetting(caseText, 'DELTA', inputFile);
    assert(abs(caseDelta - delta(index)) < 1e-12, ...
        'Unexpected DELTA in %s.', inputFile);
end
end

function validateMgkData(mgk, expectedDelta)
required = {'delta', 'omegaR0OverCs', 'omegaAOverCs', ...
    'thetaMgk', 'phiMgk', 'continuationOverlap', ...
    'baseConfig', 'references'};
assert(all(isfield(mgk, required)), ...
    'The stored MGK scan is missing required fields.');
assert(isequal(mgk.delta(:), expectedDelta), ...
    'The stored MGK triangularity points do not match the paper scan.');
assert(numel(mgk.omegaR0OverCs) == numel(expectedDelta) && ...
    numel(mgk.thetaMgk) == numel(expectedDelta) && ...
    numel(mgk.phiMgk) == numel(expectedDelta), ...
    'The stored MGK arrays have incompatible dimensions.');
assert(all(isfinite(mgk.omegaR0OverCs)) && ...
    all(real(mgk.omegaR0OverCs) < 0) && ...
    all(imag(mgk.omegaR0OverCs) > 0), ...
    'The stored MGK scan is not a growing negative-frequency branch.');

config = mgk.baseConfig;
assert(strcmpi(config.geometry.model, 'miller'));
assert(config.geometry.q == 2 && config.geometry.magneticShear == 1);
assert(config.geometry.elongation == 1 && ...
    config.geometry.elongationShear == 0 && ...
    config.geometry.triangularityShear == 0 && ...
    config.geometry.shiftDerivative == 0 && ...
    config.geometry.betaStar == 0);
assert(config.model.magneticMirror && ...
    strcmpi(config.model.electronClosure, 'adiabatic'));
assert(config.grid.numTheta == 33 && config.grid.thetaMapAlpha == 3 && ...
    config.grid.numEnergy == 16 && config.grid.numPitch == 32);
assert(~config.solver.useGpu && ...
    strcmpi(config.solver.blockPrecision, 'double'));
assert(abs(mgk.references.kyRhoS - 0.3) < 1e-12 && ...
    abs(mgk.references.majorRadiusScale - 3) < 1e-12 && ...
    abs(mgk.references.minorRadiusScale - 1) < 1e-12);

continuation = mgk.continuationOverlap(:);
continuation = continuation(isfinite(continuation));
assert(numel(continuation) == numel(expectedDelta) - 1 && ...
    min(continuation) >= 0.99, ...
    'The stored MGK roots do not form a continuous ITG branch.');
for index = 1:numel(expectedDelta)
    assert(numel(mgk.thetaMgk{index}) == numel(mgk.phiMgk{index}) && ...
        all(isfinite(mgk.thetaMgk{index})) && ...
        all(isfinite(mgk.phiMgk{index})), ...
        'Invalid stored MGK mode at delta=%+.1f.', expectedDelta(index));
end
end

function [omega, thetaBalloon, phi] = readCgyroCase(directory)
infoFile = fullfile(directory, 'out.cgyro.info');
assert(isfile(infoFile) && contains(fileread(infoFile), ...
    'Linear converged'), 'CGYRO case is not converged: %s', directory);

frequencyFile = fullfile(directory, 'out.cgyro.freq');
frequencyValues = sscanf(fileread(frequencyFile), '%f');
assert(~isempty(frequencyValues) && mod(numel(frequencyValues), 2) == 0, ...
    'Invalid CGYRO frequency history: %s', directory);
frequencyHistory = reshape(frequencyValues, 2, []).';
% CGYRO reports this standard case directly in omega*a/c_s.
omega = complex(frequencyHistory(end, 1), frequencyHistory(end, 2));

gridValues = sscanf(fileread(fullfile(directory, ...
    'out.cgyro.grids')), '%f');
assert(numel(gridValues) >= 11, 'Invalid CGYRO grid file: %s', directory);
nRadial = round(gridValues(4));
nTheta = round(gridValues(5));
assert(nRadial > 0 && nTheta > 0 && ...
    numel(gridValues) >= 11 + nRadial + nTheta, ...
    'Incomplete CGYRO grid file: %s', directory);
radialHarmonic = gridValues(12:(11 + nRadial));
theta = gridValues((12 + nRadial):(11 + nRadial + nTheta));

potentialFile = fullfile(directory, 'bin.cgyro.phib');
fileId = fopen(potentialFile, 'rb', 'ieee-le');
assert(fileId >= 0, 'Cannot open CGYRO potential output: %s', directory);
cleanup = onCleanup(@() fclose(fileId));
raw = fread(fileId, inf, 'single=>double');
clear cleanup;
frameSize = 2 * nTheta * nRadial;
assert(~isempty(raw) && mod(numel(raw), frameSize) == 0, ...
    'Invalid CGYRO potential history: %s', directory);
history = reshape(complex(raw(1:2:end), raw(2:2:end)), ...
    nTheta, nRadial, []);
finalFrame = history(:, :, end);

thetaBalloon = theta + 2 * pi * radialHarmonic.';
[thetaBalloon, order] = sort(thetaBalloon(:));
phi = finalFrame(order);
end

function [cgyro, mgk, overlap] = alignModes(cgyroTheta, cgyro, ...
        mgkTheta, mgk)
cgyro = normalizeAtPeak(cgyro);
mgk = mgk / max(abs(mgk));
inside = cgyroTheta >= min(mgkTheta) & cgyroTheta <= max(mgkTheta);
assert(nnz(inside) >= 8, 'Insufficient common field-line interval.');
sampledMgk = interp1(mgkTheta, mgk, cgyroTheta(inside), 'pchip');
sampledCgyro = cgyro(inside);
phaseProduct = sum(conj(sampledMgk) .* sampledCgyro);
assert(abs(phaseProduct) > eps, 'Mode phase alignment is ill-conditioned.');
phase = phaseProduct / abs(phaseProduct);
mgk = phase * mgk;
sampledMgk = phase * sampledMgk;
overlap = abs(sampledMgk' * sampledCgyro) / ...
    (norm(sampledMgk) * norm(sampledCgyro));
end

function mode = normalizeAtPeak(mode)
scale = max(abs(mode));
assert(scale > 0, 'Cannot normalize a zero mode.');
mode = mode / scale;
[~, peak] = max(abs(mode));
mode = mode * exp(-1i * angle(mode(peak)));
end

function plotComparison(delta, mgkOmega, cgyroOmega, thetaMgk, phiMgk, ...
        thetaCgyro, phiCgyro, displayed, outputFile)
mgkColor = [0.00, 0.45, 0.70];
cgyroColor = [0.90, 0.62, 0.00];
dark = [0.12, 0.12, 0.12];
figureHandle = figure('Visible', 'off', 'Color', 'white', ...
    'Units', 'inches', 'Position', [0.5, 0.5, 7.15, 4.55]);
layout = tiledlayout(figureHandle, 2, 2, ...
    'TileSpacing', 'compact', 'Padding', 'compact');

axisHandle = nexttile(layout, 1);
axisFrequency = axisHandle;
hold(axisHandle, 'on');
plot(axisHandle, delta, real(mgkOmega), '-o', 'Color', mgkColor, ...
    'LineWidth', 1.25, 'MarkerSize', 3.8, 'MarkerFaceColor', 'white', ...
    'HandleVisibility', 'off');
plot(axisHandle, delta, real(cgyroOmega), '-s', 'Color', cgyroColor, ...
    'LineWidth', 1.1, 'MarkerSize', 3.8, 'MarkerFaceColor', 'white', ...
    'HandleVisibility', 'off');
plot(axisHandle, delta, imag(mgkOmega), '--o', 'Color', mgkColor, ...
    'LineWidth', 1.25, 'MarkerSize', 3.8, 'MarkerFaceColor', 'white', ...
    'HandleVisibility', 'off');
plot(axisHandle, delta, imag(cgyroOmega), '--s', 'Color', cgyroColor, ...
    'LineWidth', 1.1, 'MarkerSize', 3.8, 'MarkerFaceColor', 'white', ...
    'HandleVisibility', 'off');
yline(axisHandle, 0, ':', 'Color', [0.55, 0.55, 0.55], ...
    'LineWidth', 0.55, 'HandleVisibility', 'off');
hReal = plot(axisHandle, NaN, NaN, '-', 'Color', dark, ...
    'LineWidth', 1.25, 'DisplayName', '$\omega_r$ or Re $\phi$');
hImag = plot(axisHandle, NaN, NaN, '--', 'Color', dark, ...
    'LineWidth', 1.25, 'DisplayName', '$\gamma$ or Im $\phi$');
hMgk = plot(axisHandle, NaN, NaN, '-o', 'Color', mgkColor, ...
    'LineWidth', 1.15, 'MarkerSize', 3.6, ...
    'MarkerFaceColor', 'white', 'DisplayName', 'MGK');
hCgyro = plot(axisHandle, NaN, NaN, '-s', 'Color', cgyroColor, ...
    'LineWidth', 1.05, 'MarkerSize', 3.6, ...
    'MarkerFaceColor', 'white', 'DisplayName', 'CGYRO');
xlabel(axisHandle, '$\delta$', 'Interpreter', 'latex');
ylabel(axisHandle, '$\omega a/c_s$', 'Interpreter', 'latex');
title(axisHandle, '(a)', 'FontWeight', 'normal');
xlim(axisHandle, [-0.44, 0.44]);
axisHandle.XTick = delta;
allFrequencies = [real(mgkOmega); imag(mgkOmega); ...
    real(cgyroOmega); imag(cgyroOmega)];
frequencyRange = max(allFrequencies) - min(allFrequencies);
ylim(axisHandle, [min(allFrequencies) - 0.08 * frequencyRange, ...
    max(allFrequencies) + 0.08 * frequencyRange]);
grid(axisHandle, 'on');
box(axisHandle, 'on');
formatAxis(axisHandle);

letters = 'bcd';
for panel = 1:numel(displayed)
    index = displayed(panel);
    axisHandle = nexttile(layout, panel + 1);
    hold(axisHandle, 'on');
    mgkMarkerIndices = unique(round(linspace(1, ...
        numel(thetaMgk{index}), 13)));
    cgyroMarkerIndices = unique(round(linspace(1, ...
        numel(thetaCgyro{index}), 17)));
    plot(axisHandle, thetaMgk{index} / pi, real(phiMgk{index}), '-o', ...
        'Color', mgkColor, 'LineWidth', 1.15, 'MarkerSize', 2.3, ...
        'MarkerIndices', mgkMarkerIndices, 'MarkerFaceColor', 'white', ...
        'HandleVisibility', 'off');
    plot(axisHandle, thetaCgyro{index} / pi, ...
        real(phiCgyro{index}), '-s', 'Color', cgyroColor, ...
        'LineWidth', 1.0, 'MarkerSize', 2.2, ...
        'MarkerIndices', cgyroMarkerIndices, 'MarkerFaceColor', 'white', ...
        'HandleVisibility', 'off');
    plot(axisHandle, thetaMgk{index} / pi, imag(phiMgk{index}), '--o', ...
        'Color', mgkColor, 'LineWidth', 1.15, 'MarkerSize', 2.3, ...
        'MarkerIndices', mgkMarkerIndices, 'MarkerFaceColor', 'white', ...
        'HandleVisibility', 'off');
    plot(axisHandle, thetaCgyro{index} / pi, ...
        imag(phiCgyro{index}), '--s', 'Color', cgyroColor, ...
        'LineWidth', 1.0, 'MarkerSize', 2.2, ...
        'MarkerIndices', cgyroMarkerIndices, 'MarkerFaceColor', 'white', ...
        'HandleVisibility', 'off');
    yline(axisHandle, 0, ':', 'Color', [0.55, 0.55, 0.55], ...
        'LineWidth', 0.55, 'HandleVisibility', 'off');
    xlabel(axisHandle, '$\theta/\pi$', 'Interpreter', 'latex');
    ylabel(axisHandle, '$\phi/\max|\phi|$', 'Interpreter', 'latex');
    deltaLabel = sprintf('%+.1f', delta(index));
    if abs(delta(index)) < 10 * eps
        deltaLabel = '0';
    end
    title(axisHandle, sprintf('(%c)  $\\delta=%s$', ...
        letters(panel), deltaLabel), 'Interpreter', 'latex', ...
        'FontWeight', 'normal');
    xlim(axisHandle, [-4, 4]);
    ylim(axisHandle, [-1.05, 1.05]);
    axisHandle.XTick = -4:2:4;
    axisHandle.YTick = [-1, -0.5, 0, 0.5, 1];
    grid(axisHandle, 'on');
    box(axisHandle, 'on');
    formatAxis(axisHandle);
end

legendHandle = legend(axisFrequency, ...
    [hReal, hImag, hMgk, hCgyro], ...
    'Location', 'southoutside', 'Orientation', 'horizontal', ...
    'NumColumns', 4, 'Interpreter', 'latex');
legendHandle.Layout.Tile = 'south';
legendHandle.Box = 'off';
legendHandle.FontSize = 7.0;

exportgraphics(figureHandle, outputFile, 'ContentType', 'vector', ...
    'BackgroundColor', 'white');
close(figureHandle);
end

function formatAxis(axisHandle)
axisHandle.FontName = 'Times New Roman';
axisHandle.FontSize = 7.3;
axisHandle.LineWidth = 0.6;
axisHandle.TickDir = 'out';
axisHandle.GridAlpha = 0.12;
axisHandle.MinorGridAlpha = 0.08;
end

function text = readExactText(fileName)
fileId = fopen(fileName, 'rb');
assert(fileId >= 0, 'Cannot open input file: %s', fileName);
cleanup = onCleanup(@() fclose(fileId));
bytes = fread(fileId, inf, '*uint8').';
clear cleanup;
text = char(bytes);
end

function normalized = normalizeDeltaLine(text, fileName)
[first, last] = regexp(text, '(?m)^DELTA=[^\r\n]*');
assert(isscalar(first), ...
    'Expected exactly one DELTA line in %s.', fileName);
normalized = [text(1:(first - 1)), 'DELTA=@DELTA@', ...
    text((last + 1):end)];
end

function value = readNumericSetting(text, key, fileName)
pattern = ['(?m)^', regexptranslate('escape', key), '=([^\r\n]*)'];
tokens = regexp(text, pattern, 'tokens');
assert(isscalar(tokens), ...
    'Expected exactly one %s setting in %s.', key, fileName);
value = str2double(strtrim(tokens{1}{1}));
assert(isfinite(value), 'Invalid numeric %s setting in %s.', key, fileName);
end
