function data = build_paper_comparison()
% Build the Section 4.2 figure from the existing exact-Rewoldt benchmark.

outputDir = fileparts(mfilename('fullpath'));
projectRoot = fileparts(fileparts(fileparts(outputDir)));
sourceFile = fullfile(projectRoot, 'analysis', ...
    'cbc_rewoldt2007_cpu_mapped_scan.mat');
referenceFile = fullfile(projectRoot, 'analysis', ...
    'rewoldt2007_fig2_digitized.csv');
cgyroFile = fullfile(projectRoot, 'cgyro_cbc_branch_audit_20260813', ...
    'data', '01_cgyro_same_branch_curve.csv');
mgkModeFile = fullfile(projectRoot, 'analysis', ...
    'mgk_rewoldt2007_fig5a_tem_mode.csv');
fullModeFile = fullfile(projectRoot, 'analysis', ...
    'rewoldt2007_fig5a_digitized.csv');

source = load(sourceFile);
validateSource(source);
kyRhoS = source.data.kyRhoS(:);
itgOmega = source.itg.omega(:);
temOmega = source.tem.omega(:);
aOverR = source.aOverR;
itgOmegaR = real(itgOmega);
itgGamma = imag(itgOmega);
temOmegaR = real(temOmega);
temGamma = imag(temOmega);
itgOmegaR(~isfinite(itgOmega)) = NaN;
itgGamma(~isfinite(itgOmega)) = NaN;
temOmegaR(~isfinite(temOmega)) = NaN;
temGamma(~isfinite(temOmega)) = NaN;

[crossingInterval, crossingKy] = locateCrossing( ...
    kyRhoS, itgOmega, temOmega);
dominantBranch = repmat("TEM", numel(kyRhoS), 1);
itgDominant = isfinite(itgOmega) & ...
    imag(itgOmega) >= imag(temOmega);
dominantBranch(itgDominant) = "ITG";
assert(all(dominantBranch == string(source.data.dominantBranch)), ...
    'Stored dominant-branch labels are inconsistent with the branch arrays.');

data = table(kyRhoS, ...
    itgOmegaR, itgGamma, temOmegaR, temGamma, ...
    aOverR * itgOmegaR, aOverR * itgGamma, ...
    aOverR * temOmegaR, aOverR * temGamma, ...
    dominantBranch, source.itg.modeOverlap(:), source.tem.modeOverlap(:), ...
    source.itg.eigenResidual(:), source.tem.eigenResidual(:), ...
    source.itg.fieldResidual(:), source.tem.fieldResidual(:), ...
    'VariableNames', {'kyRhoS', ...
    'itgOmegaRoverCs', 'itgGammaRoverCs', ...
    'temOmegaRoverCs', 'temGammaRoverCs', ...
    'itgOmegaAoverCs', 'itgGammaAoverCs', ...
    'temOmegaAoverCs', 'temGammaAoverCs', ...
    'dominantBranch', 'itgModeOverlap', 'temModeOverlap', ...
    'itgEigenResidual', 'temEigenResidual', ...
    'itgFieldResidual', 'temFieldResidual'});

referenceData = readtable(referenceFile, 'TextType', 'string');
validateReference(referenceData, aOverR);
cgyroData = readtable(cgyroFile, 'TextType', 'string');
validateCgyro(cgyroData);
mgkMode = readtable(mgkModeFile);
fullMode = readtable(fullModeFile);
validateModeStructure(mgkMode, fullMode);
sourceMetadata = struct( ...
    'sourceFile', sourceFile, ...
    'parameterSet', string(source.parameterSet), ...
    'executionProfile', string(source.executionProfile), ...
    'config', source.config, ...
    'aOverR', aOverR, ...
    'frequencyReference', source.frequencyReference, ...
    'rhoS', source.rhoS);

csvFile = fullfile(outputDir, 'cbc_kinetic_itg_tem_branches.csv');
matFile = fullfile(outputDir, 'cbc_kinetic_itg_tem_branches.mat');
writetable(data, csvFile);
save(matFile, 'data', 'referenceData', 'cgyroData', 'mgkMode', 'fullMode', ...
    'sourceMetadata', ...
    'crossingInterval', 'crossingKy');

figureDirectory = fullfile(fileparts(projectRoot), 'paper', 'figures');
if ~isfolder(figureDirectory)
    mkdir(figureDirectory);
end
figureFile = fullfile(figureDirectory, ...
    'cbc_kinetic_itg_tem_branches.pdf');
plotBranches(data, referenceData, cgyroData, mgkMode, fullMode, figureFile);

fprintf('Source benchmark: %s (%s)\n', ...
    source.parameterSet, source.executionProfile);
fprintf('ITG range: %.3f <= ky*rho_s <= %.3f; TEM range: %.3f <= ky*rho_s <= %.3f\n', ...
    min(kyRhoS(isfinite(itgOmega))), max(kyRhoS(isfinite(itgOmega))), ...
    min(kyRhoS(isfinite(temOmega))), max(kyRhoS(isfinite(temOmega))));
fprintf('Growth-rate crossing: %.3f < ky*rho_s < %.3f (linear estimate %.4f)\n', ...
    crossingInterval(1), crossingInterval(2), crossingKy);
fprintf('Minimum stored continuation overlap: ITG %.6f, TEM %.6f\n', ...
    min(source.itg.modeOverlap, [], 'omitnan'), ...
    min(source.tem.modeOverlap, [], 'omitnan'));
fprintf('Data: %s\n', csvFile);
fprintf('Figure: %s\n', figureFile);
end

function validateSource(source)
required = {'parameterSet', 'executionProfile', 'data', 'config', ...
    'rhoS', 'frequencyReference', 'itg', 'tem', 'aOverR'};
assert(all(isfield(source, required)), ...
    'The stored Rewoldt benchmark is missing required fields.');
assert(string(source.parameterSet) == "rewoldt2007");
assert(string(source.executionProfile) == "cpu_mapped33");

config = source.config;
relativeTolerance = 1e-10;
assert(abs(config.physical.minorRadius / ...
    config.physical.majorRadius - 0.18) < relativeTolerance);
assert(abs(config.physical.majorRadius / ...
    config.physical.densityGradientLength - 2.22) < relativeTolerance);
assert(abs(config.physical.majorRadius / ...
    config.physical.ionTemperatureGradientLength - 6.92) < relativeTolerance);
assert(abs(config.physical.majorRadius / ...
    config.physical.electronTemperatureGradientLength - 6.92) < ...
    relativeTolerance);
assert(abs(config.geometry.q - 1.4) < relativeTolerance);
assert(abs(config.geometry.magneticShear - 0.776) < relativeTolerance);
assert(config.physical.ionTemperature == config.physical.electronTemperature);
assert(config.physical.electronBeta == 0);
assert(config.model.magneticMirror && ~config.model.aparallel);
assert(strcmpi(config.model.parallelBoundary, 'open'));
assert(~config.solver.useGpu && strcmpi(config.solver.blockPrecision, 'double'));
assert(config.grid.thetaMin == -4 * pi && config.grid.thetaMax == 4 * pi);
assert(config.grid.numTheta == 33 && config.grid.thetaMapAlpha == 3);
assert(config.grid.numEnergy == 16 && config.grid.numPitch == 32 && ...
    config.grid.numBouncePoints == 48);

numPoints = height(source.data);
branchFields = {'omega', 'eigenResidual', 'fieldResidual', ...
    'modeOverlap', 'runtimeSeconds'};
for index = 1:numel(branchFields)
    name = branchFields{index};
    assert(numel(source.itg.(name)) == numPoints && ...
        numel(source.tem.(name)) == numPoints, ...
        'Stored branch arrays have incompatible dimensions.');
end
kyRhoS = source.data.kyRhoS(:);
assert(numPoints > 2 && kyRhoS(1) == 0.1 && kyRhoS(end) == 1.0);
assert(all(diff(kyRhoS) > 0));

itgValid = isfinite(source.itg.omega(:));
temValid = isfinite(source.tem.omega(:));
assert(isequal(find(itgValid), (1:nnz(itgValid)).'));
assert(all(temValid));
assert(all(real(source.itg.omega(itgValid)) < 0));
assert(all(real(source.tem.omega(temValid)) > 0));
assert(all(isfinite(source.itg.eigenResidual(itgValid))) && ...
    all(isfinite(source.tem.eigenResidual(temValid))));
assert(abs(source.aOverR - 0.36) < relativeTolerance);
end

function validateReference(reference, aOverR)
required = {'sourceCode', 'kThetaRhoI', 'gammaCsOverLne', ...
    'omegaCsOverLne', 'gammaAOverCs', 'omegaAOverCs'};
assert(all(ismember(required, reference.Properties.VariableNames)));
assert(all(ismember(unique(reference.sourceCode), ["GTC"; "GT3D"])));
normalizationScale = aOverR * 2.22;
assert(max(abs(reference.gammaAOverCs - ...
    normalizationScale * reference.gammaCsOverLne)) < 1e-6);
assert(max(abs(reference.omegaAOverCs - ...
    normalizationScale * reference.omegaCsOverLne)) < 1e-6);
end

function validateCgyro(cgyro)
required = {'kyRhoS', 'omegaAoverCs', 'gammaAoverCs'};
assert(all(ismember(required, cgyro.Properties.VariableNames)), ...
    'The CGYRO same-branch curve is missing required columns.');
assert(all(isfinite(cgyro.kyRhoS)) && ...
    all(isfinite(cgyro.omegaAoverCs)) && ...
    all(isfinite(cgyro.gammaAoverCs)));
assert(all(diff(cgyro.kyRhoS) > 0));
assert(abs(cgyro.kyRhoS(1) - 0.1) < 1e-12 && ...
    abs(cgyro.kyRhoS(end) - 1.0) < 1e-12);
end

function validateModeStructure(mgkMode, fullMode)
assert(all(ismember({'theta', 'realPhi', 'imagPhi'}, ...
    mgkMode.Properties.VariableNames)));
assert(all(ismember({'theta', 'fullRealPhi', 'fullImagPhi'}, ...
    fullMode.Properties.VariableNames)));
assert(all(isfinite(fullMode.theta)) && ...
    all(isfinite(fullMode.fullRealPhi)) && ...
    all(isfinite(fullMode.fullImagPhi)));
assert(min(mgkMode.theta) <= -4 * pi && max(mgkMode.theta) >= 4 * pi);
[~, centerIndex] = min(abs(mgkMode.theta));
assert(abs(mgkMode.realPhi(centerIndex) - 1) < 1e-8);
end

function [interval, crossing] = locateCrossing(kyRhoS, itgOmega, temOmega)
common = isfinite(itgOmega) & isfinite(temOmega);
commonKy = kyRhoS(common);
difference = imag(itgOmega(common)) - imag(temOmega(common));
indices = find(difference(1:(end - 1)) .* difference(2:end) < 0);
assert(numel(indices) == 1, ...
    'Expected exactly one ITG--TEM growth-rate crossing.');
index = indices(1);
interval = commonKy(index:(index + 1)).';
crossing = commonKy(index) - difference(index) * ...
    (commonKy(index + 1) - commonKy(index)) / ...
    (difference(index + 1) - difference(index));
end

function plotBranches(data, reference, cgyro, mgkMode, fullMode, outputFile)
mgkColor = [0.00, 0.45, 0.70];
cgyroColor = [0.90, 0.62, 0.00];
gtcColor = [0.00, 0.62, 0.45];
gt3dColor = [0.80, 0.47, 0.65];
fullColor = [0.84, 0.37, 0.00];
gtc = reference.sourceCode == "GTC";
gt3d = reference.sourceCode == "GT3D";

figureHandle = figure('Visible', 'off', 'Color', 'white', ...
    'Units', 'inches', 'Position', [0.5, 0.5, 7.15, 2.85], ...
    'Renderer', 'painters');
layout = tiledlayout(figureHandle, 1, 3, ...
    'TileSpacing', 'compact', 'Padding', 'compact');

axisOmega = nexttile(layout, 1);
hold(axisOmega, 'on');
hItg = plot(axisOmega, data.kyRhoS, data.itgOmegaAoverCs, '-', ...
    'Color', mgkColor, 'LineWidth', 1.45, 'DisplayName', 'MGK ITG');
hTem = plot(axisOmega, data.kyRhoS, data.temOmegaAoverCs, '--', ...
    'Color', mgkColor, 'LineWidth', 1.45, 'DisplayName', 'MGK TEM');
hCgyro = plot(axisOmega, cgyro.kyRhoS, cgyro.omegaAoverCs, 'd', ...
    'LineStyle', 'none', ...
    'Color', cgyroColor, 'MarkerFaceColor', 'white', 'MarkerSize', 3.8, ...
    'LineWidth', 0.9, 'DisplayName', 'CGYRO');
hGtc = plot(axisOmega, reference.kThetaRhoI(gtc), ...
    reference.omegaAOverCs(gtc), 'o', 'LineStyle', 'none', ...
    'Color', gtcColor, 'MarkerFaceColor', 'white', 'MarkerSize', 4.2, ...
    'LineWidth', 0.9, 'DisplayName', 'GTC');
hGt3d = plot(axisOmega, reference.kThetaRhoI(gt3d), ...
    reference.omegaAOverCs(gt3d), '^', 'LineStyle', 'none', ...
    'Color', gt3dColor, 'MarkerFaceColor', 'white', 'MarkerSize', 4.4, ...
    'LineWidth', 0.9, 'DisplayName', 'GT3D');
yline(axisOmega, 0, ':', 'Color', [0.55, 0.55, 0.55], ...
    'LineWidth', 0.6, 'HandleVisibility', 'off');
xlabel(axisOmega, '$k_y\rho_s$', 'Interpreter', 'latex');
ylabel(axisOmega, '$\omega_r a/c_s$', 'Interpreter', 'latex');
ylim(axisOmega, [-0.68, 0.66]);
title(axisOmega, '(a)', 'FontWeight', 'normal');
formatAxis(axisOmega);

axisGamma = nexttile(layout, 2);
hold(axisGamma, 'on');
plot(axisGamma, data.kyRhoS, data.itgGammaAoverCs, '-', ...
    'Color', mgkColor, 'LineWidth', 1.45, 'HandleVisibility', 'off');
plot(axisGamma, data.kyRhoS, data.temGammaAoverCs, '--', ...
    'Color', mgkColor, 'LineWidth', 1.45, 'HandleVisibility', 'off');
plot(axisGamma, cgyro.kyRhoS, cgyro.gammaAoverCs, 'd', ...
    'LineStyle', 'none', ...
    'Color', cgyroColor, 'MarkerFaceColor', 'white', 'MarkerSize', 3.8, ...
    'LineWidth', 0.9, 'HandleVisibility', 'off');
plot(axisGamma, reference.kThetaRhoI(gtc), ...
    reference.gammaAOverCs(gtc), 'o', 'LineStyle', 'none', ...
    'Color', gtcColor, 'MarkerFaceColor', 'white', 'MarkerSize', 4.2, ...
    'LineWidth', 0.9, 'HandleVisibility', 'off');
plot(axisGamma, reference.kThetaRhoI(gt3d), ...
    reference.gammaAOverCs(gt3d), '^', 'LineStyle', 'none', ...
    'Color', gt3dColor, 'MarkerFaceColor', 'white', 'MarkerSize', 4.4, ...
    'LineWidth', 0.9, 'HandleVisibility', 'off');
yline(axisGamma, 0, ':', 'Color', [0.55, 0.55, 0.55], ...
    'LineWidth', 0.6, 'HandleVisibility', 'off');
xlabel(axisGamma, '$k_y\rho_s$', 'Interpreter', 'latex');
ylabel(axisGamma, '$\gamma a/c_s$', 'Interpreter', 'latex');
ylim(axisGamma, [0, 0.19]);
title(axisGamma, '(b)', 'FontWeight', 'normal');
formatAxis(axisGamma);

axisMode = nexttile(layout, 3);
hold(axisMode, 'on');
hMgkReal = plot(axisMode, mgkMode.theta, mgkMode.realPhi, '-', ...
    'Color', mgkColor, 'LineWidth', 1.35, 'DisplayName', 'MGK Re $\phi$');
hFullReal = plot(axisMode, fullMode.theta, fullMode.fullRealPhi, '-o', ...
    'Color', fullColor, 'LineWidth', 0.85, 'MarkerFaceColor', 'white', ...
    'MarkerIndices', 1:4:height(fullMode), 'MarkerSize', 2.8, ...
    'DisplayName', 'FULL Re $\phi$');
hMgkImag = plot(axisMode, mgkMode.theta, mgkMode.imagPhi, '--', ...
    'Color', mgkColor, 'LineWidth', 1.35, 'DisplayName', 'MGK Im $\phi$');
hFullImag = plot(axisMode, fullMode.theta, fullMode.fullImagPhi, '--o', ...
    'Color', fullColor, 'LineWidth', 0.85, 'MarkerFaceColor', 'white', ...
    'MarkerIndices', 1:4:height(fullMode), 'MarkerSize', 2.8, ...
    'DisplayName', 'FULL Im $\phi$');
yline(axisMode, 0, ':', 'Color', [0.55, 0.55, 0.55], ...
    'LineWidth', 0.6, 'HandleVisibility', 'off');
xlabel(axisMode, '$\theta$', 'Interpreter', 'latex');
ylabel(axisMode, '$\phi(\theta)/\phi(0)$', 'Interpreter', 'latex');
xlim(axisMode, [-7, 7]);
ylim(axisMode, [-0.08, 1.05]);
axisMode.XTick = -6:3:6;
axisMode.YTick = [0, 0.5, 1.0];
title(axisMode, '(c)', 'FontWeight', 'normal');
grid(axisMode, 'on');
box(axisMode, 'on');
axisMode.FontName = 'Times New Roman';
axisMode.FontSize = 7.5;
axisMode.LineWidth = 0.6;
axisMode.TickDir = 'out';
axisMode.GridAlpha = 0.12;
modeLegend = legend(axisMode, ...
    [hMgkReal, hFullReal, hMgkImag, hFullImag], ...
    'Location', 'northwest', 'NumColumns', 2, ...
    'Interpreter', 'latex');
modeLegend.Box = 'off';
modeLegend.FontSize = 5.8;

legendHandle = legend(axisOmega, [hItg, hTem, hCgyro, hGtc, hGt3d], ...
    'Location', 'southoutside', 'Orientation', 'horizontal', ...
    'NumColumns', 5);
legendHandle.Layout.Tile = 'south';
legendHandle.Box = 'off';
legendHandle.FontSize = 7.2;

exportgraphics(figureHandle, outputFile, 'ContentType', 'vector', ...
    'BackgroundColor', 'white');
close(figureHandle);
end

function formatAxis(axisHandle)
xlim(axisHandle, [0.1, 1.0]);
axisHandle.XTick = 0.1:0.1:1.0;
grid(axisHandle, 'on');
box(axisHandle, 'on');
axisHandle.FontName = 'Times New Roman';
axisHandle.FontSize = 7.5;
axisHandle.LineWidth = 0.6;
axisHandle.TickDir = 'out';
axisHandle.GridAlpha = 0.12;
end
